# Settle as a generated sub-SMC: a checkable membership predicate.
#
# Claim under test (blog post "The Category Settle", book Appendix E,
# PROOF-ROADMAP P3): Settle is the sub-SMC of OPetri generated by two
# transition shapes,
#
#     send   : balance -> pending
#     settle : pending -> balance
#
# closed under gluing along balance places (pushout, `glue`) and under
# disjoint union (⊗, `merge`/`+`).  This file gives
#
#   * `is_settle_generated(lpn)` / `settle_reason(lpn)` — decides whether a
#     LabelledPetriNet is in the class, with a reason string when it is not;
#   * `send_net`, `settle_net`, `settle_channel` — the generators as open
#     nets, and the channel as their composite;
#   * `SettleNet` — a Catlab ACSet whose schema carries the typing as data
#     (`skind ∈ {balance, pending}`, `tkind ∈ {send, settle}`), with
#     `to_settle_net` (type inference) and `forget_kinds` (the forgetful
#     functor back to LabelledPetriNet, a Δ-migration along the schema
#     inclusion).
#
# What membership means, precisely.  A net is *Settle-generated* iff there is
# a typing  kind : S -> {balance, pending}  such that
#
#   (T1) every transition has exactly one input and exactly one output
#        species, each with multiplicity 1, and they are distinct;
#   (T2) every transition goes balance -> pending (then it is a `send`) or
#        pending -> balance (then it is a `settle`);
#   (T3) every pending place has exactly one producer (a send) and exactly
#        one consumer (a settle).
#
# Balance places are unconstrained: any number of sends out, settles in,
# including none (a party with no channels is the monoidal unit's neighbour).
# (T2) says the place graph (places adjacent when a transition joins them) is
# bipartite; (T3) picks which side is `pending`.  Where both sides satisfy
# (T3) — a 2-cycle x -> t1 -> y -> t2 -> x — both typings are valid and the
# net is in the class either way (it is the channel x -> x with y as pending).
#
# See docs/settle-closure.md for what the checks do and do not establish.

using Catlab.CategoricalAlgebra: compose, migrate, copy_parts!, legs

export is_settle_generated, settle_reason, settle_typing,
       send_net, settle_net, settle_channel,
       SchSettleNet, SettleNet, to_settle_net, forget_kinds, is_well_typed_settle

# ---------------------------------------------------------------------------
# 1. Membership predicate
# ---------------------------------------------------------------------------

_sname(lpn, s) = has_subpart(lpn, :sname) ? String(sname(lpn, s)) : "s$s"
_tname(lpn, t) = has_subpart(lpn, :tname) ? String(tname(lpn, t)) : "t$t"

"""
    settle_typing(lpn; boundary=Int[]) -> (places::Dict{Int,Symbol}, transitions::Dict{Int,Symbol}) or String

Infer the balance/pending typing of species and the send/settle typing of
transitions.  Returns the two dictionaries (keyed by part index) when `lpn`
is Settle-generated, otherwise a reason string explaining the first
violation found.  Reason strings begin with a stable tag:

  `fan-in`, `fan-out`, `no-input`, `no-output`, `self-loop`, `not-bipartite`,
  `pending-degree`.

`boundary` lists species indices that are legs of an open net.  A boundary
pending is exempt from (T3) — it is half a channel waiting for the other
half, which is exactly what the generators `send_net`/`settle_net` are.
The closed class (no boundary) is what `glue`/`⊗` of closed members must
land in.
"""
function settle_typing(lpn::AbstractPetriNet; boundary::AbstractVector{Int} = Int[])
    S, T = ns(lpn), nt(lpn)
    # (T1) shape of every transition
    src = zeros(Int, T); dst = zeros(Int, T)
    for t in 1:T
        ins = collect(inputs(lpn, t)); outs = collect(outputs(lpn, t))
        name = _tname(lpn, t)
        length(ins) == 0 && return "no-input: transition $name has no input place"
        length(outs) == 0 && return "no-output: transition $name has no output place"
        length(ins) > 1 && return "fan-in: transition $name has $(length(ins)) inputs " *
            "($(join(unique(_sname.(Ref(lpn), ins)), ", "))); generators have exactly one (ρ = 1, multiplicity 1)"
        length(outs) > 1 && return "fan-out: transition $name has $(length(outs)) outputs " *
            "($(join(unique(_sname.(Ref(lpn), outs)), ", "))); generators have exactly one"
        ins[1] == outs[1] && return "self-loop: transition $name reads and writes $(_sname(lpn, ins[1])); " *
            "a generator moves a token between two distinct places"
        src[t] = ins[1]; dst[t] = outs[1]
    end
    producers = zeros(Int, S); consumers = zeros(Int, S)
    for t in 1:T
        consumers[src[t]] += 1; producers[dst[t]] += 1
    end
    # (T2) bipartite 2-colouring of the place graph, per connected component
    adj = [Int[] for _ in 1:S]
    for t in 1:T
        push!(adj[src[t]], dst[t]); push!(adj[dst[t]], src[t])
    end
    colour = fill(-1, S)
    kind = Dict{Int,Symbol}()
    for root in 1:S
        colour[root] == -1 || continue
        colour[root] = 0
        comp = [root]; queue = [root]
        while !isempty(queue)
            u = popfirst!(queue)
            for v in adj[u]
                if colour[v] == -1
                    colour[v] = 1 - colour[u]; push!(comp, v); push!(queue, v)
                elseif colour[v] == colour[u]
                    return "not-bipartite: places $(_sname(lpn, u)) and $(_sname(lpn, v)) are joined by a " *
                        "transition but also lie at even distance; no balance/pending typing exists"
                end
            end
        end
        # (T3) choose the pending side
        side = c -> [s for s in comp if colour[s] == c]
        # A boundary pending is half a channel: exempt from *exactly* one producer
        # and consumer, not from *at most* one — a hub on a leg is still not Settle.
        okplace = s -> (s in boundary) ? (producers[s] <= 1 && consumers[s] <= 1) :
                                         (producers[s] == 1 && consumers[s] == 1)
        ok = c -> all(okplace, side(c))
        if length(comp) == 1
            kind[root] = :balance               # isolated place: a party with no channels
            continue
        end
        cands = [c for c in (0, 1) if ok(c)]
        if isempty(cands)
            # name the offender on the side that looks like the pending side: the
            # one whose labels say "pending", else the side with a degree > 1 place
            # (a balance with 0 producers is never the interesting culprit)
            hint0 = c -> any(s -> startswith(_sname(lpn, s), "pending"), side(c))
            overfull = c -> any(s -> producers[s] > 1 || consumers[s] > 1, side(c))
            order = hint0(1) && !hint0(0) ? (1, 0) : hint0(0) && !hint0(1) ? (0, 1) :
                    overfull(1) && !overfull(0) ? (1, 0) : (0, 1)
            for c in order, s in side(c)
                okplace(s) && continue
                return "pending-degree: no typing works — place $(_sname(lpn, s)) has $(producers[s]) producer(s) " *
                    "and $(consumers[s]) consumer(s) (a pending place needs exactly one of each), and the " *
                    "opposite side of its component also contains a place violating that"
            end
        end
        # prefer the side whose labels say "pending" when both qualify
        hint = c -> any(s -> startswith(_sname(lpn, s), "pending"), side(c))
        pend = length(cands) == 1 ? cands[1] : (hint(1) && !hint(0) ? 1 : 0)
        for s in comp
            kind[s] = colour[s] == pend ? :pending : :balance
        end
    end
    tkind = Dict{Int,Symbol}(t => (kind[src[t]] == :balance ? :send : :settle) for t in 1:T)
    (kind, tkind)
end

"""
    settle_reason(lpn) -> Union{Nothing,String}

`nothing` when `lpn` is Settle-generated, else the reason it is not.
"""
function settle_reason(lpn::AbstractPetriNet; kw...)
    r = settle_typing(lpn; kw...)
    r isa String ? r : nothing
end

"Species indices in the image of any leg of an open net."
boundary_species(o) = sort(unique(vcat((collect(l[:S]) for l in legs(o))...)))

settle_typing(o::OpenLabelledPetriNet) = settle_typing(apex(o); boundary = boundary_species(o))
settle_reason(o::OpenLabelledPetriNet) = settle_reason(apex(o); boundary = boundary_species(o))
is_settle_generated(o::OpenLabelledPetriNet) = settle_reason(o) === nothing

"""
    is_settle_generated(lpn) -> Bool

True iff `lpn` is in the class generated by `send` (balance -> pending) and
`settle` (pending -> balance) under gluing along balances and ⊗.  Use
`settle_reason` for the reason when false.  For an `OpenLabelledPetriNet`
the legs are treated as boundary (see `settle_typing`), so the generators
themselves pass; a closed `LabelledPetriNet` has no boundary.
"""
is_settle_generated(lpn::AbstractPetriNet; kw...) = settle_reason(lpn; kw...) === nothing

# ---------------------------------------------------------------------------
# 2. Generators as open nets
# ---------------------------------------------------------------------------

"""
    send_net(x, pending; name="send_\$x") -> OpenLabelledPetriNet

The generator `send : x -> pending` with legs `[x]` (input boundary) and
`[pending]` (output boundary).
"""
function send_net(x::AbstractString, pending::AbstractString; name::AbstractString = "send_$x")
    lpn = LabelledPetriNet([Symbol(x), Symbol(pending)], Symbol(name) => ([Symbol(x)] => [Symbol(pending)]))
    Open(lpn, [Symbol(x)], [Symbol(pending)])
end

"""
    settle_net(pending, y; name="settle_\$y") -> OpenLabelledPetriNet

The generator `settle : pending -> y` with legs `[pending]` and `[y]`.
"""
function settle_net(pending::AbstractString, y::AbstractString; name::AbstractString = "settle_$y")
    lpn = LabelledPetriNet([Symbol(pending), Symbol(y)], Symbol(name) => ([Symbol(pending)] => [Symbol(y)]))
    Open(lpn, [Symbol(pending)], [Symbol(y)])
end

"""
    settle_channel(x, y; tag="") -> Pflow

The channel `x -> y`: `send_xy` debits `x` into `pending_xy`, `settle_xy`
credits `y`.  Equal to `compose(send_net(x, p), settle_net(p, y))` — the
two generators glued along `pending` — which `test/test_closure.jl` checks.
`tag` disambiguates several channels between the same pair of parties
(pending and transition labels get `_tag` appended).
"""
function settle_channel(x::String, y::String; tag::String = "")
    x == y && throw(ArgumentError("a channel needs two distinct balance places (got $x twice)"))
    sfx = isempty(tag) ? "" : "_$tag"
    p = "pending_$(x)$(y)$sfx"; s = "send_$(x)$(y)$sfx"; r = "settle_$(x)$(y)$sfx"
    net = Pflow()
    place!(net, x; initial = 100)
    place!(net, y; initial = 100)
    place!(net, p; initial = 0)
    transition!(net, s)
    transition!(net, r)
    arc!(net; source = x, target = s)
    arc!(net; source = s, target = p)
    arc!(net; source = p, target = r)
    arc!(net; source = r, target = y)
    net
end

# ---------------------------------------------------------------------------
# 3. Catlab formulation: the typing as schema data
# ---------------------------------------------------------------------------

"""
`SchLabelledPetriNet` extended with the Settle typing as attributes:
`skind : S -> Kind` (balance | pending) and `tkind : T -> Kind`
(send | settle).  The schema inclusion `SchLabelledPetriNet ↪ SchSettleNet`
induces the forgetful functor `forget_kinds` (Δ-migration).
"""
@present SchSettleNet <: SchLabelledPetriNet begin
    Kind::AttrType
    skind::Attr(S, Kind)
    tkind::Attr(T, Kind)
end

@acset_type SettleNetUntyped(SchSettleNet, index = [:it, :is, :ot, :os]) <: AbstractLabelledPetriNet
const SettleNet = SettleNetUntyped{Symbol, Symbol}

"""
    to_settle_net(lpn::LabelledPetriNet) -> SettleNet

Infer the typing with `settle_typing` and record it as `skind`/`tkind`.
Throws `ArgumentError` carrying the `settle_reason` when `lpn` is not
Settle-generated — so a `SettleNet` value is itself a certificate that the
predicate passed.
"""
function to_settle_net(lpn::AbstractLabelledPetriNet)::SettleNet
    r = settle_typing(lpn)
    r isa String && throw(ArgumentError("not Settle-generated: $r"))
    skind, tkind = r
    sn = SettleNet()
    copy_parts!(sn, lpn)
    for s in 1:ns(sn); set_subpart!(sn, s, :skind, skind[s]); end
    for t in 1:nt(sn); set_subpart!(sn, t, :tkind, tkind[t]); end
    sn
end

"""
    forget_kinds(sn::SettleNet) -> LabelledPetriNet

The forgetful functor `SettleNet -> LabelledPetriNet`: pull back along the
schema inclusion (Catlab `migrate` with the identity-on-the-image maps).
"""
function forget_kinds(sn::SettleNet)::LabelledPetriNet
    FOb  = Dict(:S => :S, :T => :T, :I => :I, :O => :O, :Name => :Name)
    FHom = Dict(:is => :is, :it => :it, :os => :os, :ot => :ot, :sname => :sname, :tname => :tname)
    migrate(LabelledPetriNet, sn, FOb, FHom)
end

"""
    is_well_typed_settle(sn::SettleNet) -> Bool

Check the *recorded* typing rather than inferring one: every transition is a
`send` from a `balance` to a `pending` or a `settle` from a `pending` to a
`balance`, with multiplicity 1, and every `pending` has one producer and one
consumer.  `to_settle_net` always produces a well-typed net; this is the
check for nets built by hand or by composition.
"""
function is_well_typed_settle(sn::SettleNet)::Bool
    producers = zeros(Int, ns(sn)); consumers = zeros(Int, ns(sn))
    for t in 1:nt(sn)
        ins = collect(inputs(sn, t)); outs = collect(outputs(sn, t))
        (length(ins) == 1 && length(outs) == 1 && ins[1] != outs[1]) || return false
        a, b = sn[ins[1], :skind], sn[outs[1], :skind]
        k = sn[t, :tkind]
        (k == :send && a == :balance && b == :pending) || (k == :settle && a == :pending && b == :balance) || return false
        consumers[ins[1]] += 1; producers[outs[1]] += 1
    end
    all(s -> sn[s, :skind] == :balance || (producers[s] == 1 && consumers[s] == 1), 1:ns(sn))
end
